- name: Clean TF cache
  hosts: localhost,all
  tasks:
    - name: Clean TF cache
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "log.txt"
        - "/tmp/blockscout-{{ group_names[0] }}-{{ chain }}"
        - "/tmp/files-{{ group_names[0] }}"
