- name: Deploy BlockScout
  hosts: all
  tasks:
   - block:
     - name: Generate local variables
       import_role: 
         name: ssm_vars
         tasks_from: dev.yml
       tags:
         - build
     - name: Build the local BlockScout instance first
       import_role:
         name: build
       tags:
         - build
     - name: Update the production variables
       import_role:
         name: ssm_vars
         tasks_from: prod.yml
       when: env_vars is defined
       tags:
         - update_vars
     - name: Deploy the production BlockScout instance
       import_role:
         name: deploy
     always:
     - import_role:
         name: s3
         tasks_from: remote-files.yml
       when: backend | bool
