- name: Destroy infrastructure
  hosts: all
  tasks:
    - import_role:
        role: infrastructure
        tasks_from: destroy.yml
      when: "confirmation | bool and inventory_hostname == groups[group_names[0]][0]"
  vars_prompt:
    - name: "confirmation"
      prompt: "Are you sure you want to destroy all the infra?"
      default: False
